    /*CRIAÇÃO DE TABELA, PARENTESES APÓS NOME DA TABELA E DEFINIR COLUNAS*/
    /*DEVE SE UTILIZAR VIRGULA PARA SEPARAR COLUNAS CRIADAS*/
    /*DEVE SE UTILIZXAR PONTO E VIRGULA NO FIM DE TODO CODIGO SQL*/
CREATE TABLE usuarios(
    /*COLUNA NOME TIPO VARCHAR(TEXTO) E MAX 50 UNIDADES*/
    nome VARCHAR(50),
    /*COLUNA EMAIL TIPO VARCHAR(TEXTO) E MAX 100 UNIDADES*/
    email VARCHAR(100),
    /*COLUNA IDADE CRIADA COM O TIPO INTEIRO*/
    idade INT
);